DROP TABLE IF EXISTS comments;

CREATE TABLE comments (
id SERIAL PRIMARY KEY,
username VARCHAR(200) NOT NULL,
comment TEXT not NULL,
image_id INTEGER REFERENCES images(id) NOT NULL,
created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
